#!/bin/bash

#SBATCH --partition=gpuL
#SBATCH --gpus=1
#SBATCH -c 8
#SBATCH --ntasks=1
#SBATCH --time=1-0
#SBATCH --output=/dev/null

# Usage: sbatch process.job <dataset> <filterbank> [--encode]
set -euo pipefail

DATASET="${1:?Usage: sbatch encode.job <dataset> <filterbank> [--encode]}"
FILTERBANK="${2:?Usage: sbatch encode.job <dataset> <filterbank> [--encode]}"
ENCODE_FLAG=""
if [[ "${3:-}" == "--encode" ]]; then
  ENCODE_FLAG="--encode"
fi

module load apps/binapps/conda/miniforge3/25.9.1

BASE="/mnt/iusers01/fse-ugpgt01/compsci01/x06213zr/scratch/bio-inspired-sonar-for-underwater-object-detection"
RUN_DIR="$BASE/runs/processing_$(date +%Y-%m-%d_%H-%M)"
mkdir -p "$RUN_DIR"

exec > >(tee -a "$RUN_DIR/output.log") 2>&1

echo "===== Job started at $(date) ====="
echo "RUN_ID: $SLURM_JOB_ID"

echo "Installing requirements..."
cd $BASE
python -m venv .venv
source ./.venv/bin/activate
pip install --quiet -r "$BASE/requirements/requirements-cuda.txt"

echo "===== Processing started at $(date) ====="
python -u -m src.run_process --dataset "$DATASET" --filterbank "$FILTERBANK" $ENCODE_FLAG

echo "Archiving processed data..."
if [[ -n "$ENCODE_FLAG" ]]; then
    OUTPUT_DIR="${DATASET}-${FILTERBANK}-spikes"
else
    OUTPUT_DIR="${DATASET}-${FILTERBANK}-spectrograms"
fi
cd $BASE/processed
tar cf "${OUTPUT_DIR}.tar" "${OUTPUT_DIR}"
rm -rf "${OUTPUT_DIR}"
echo "===== Processing finished at $(date) ====="
