#!/bin/bash

#SBATCH --partition=gpuL
#SBATCH --gpus=1
#SBATCH -c 8
#SBATCH --ntasks=1
#SBATCH --time=1-0

# Usage: sbatch train.job <model>
set -euo pipefail

MODEL="${1:?Usage: sbatch train.job <cnn|snn|snn_encoded>}"

module load apps/binapps/conda/miniforge3/25.9.1
module load libs/cuda/12.4.1

BASE="/mnt/iusers01/fse-ugpgt01/compsci01/x06213zr/scratch/bio-inspired-sonar-for-underwater-object-detection"

RUN_DIR="$BASE/runs/${MODEL}_$(date +%Y-%m-%d_%H-%M)"
mkdir -p "$RUN_DIR/plots"

exec > >(tee -a "$RUN_DIR/output.log") 2>&1

echo "===== Job started at $(date) ====="
echo "RUN_ID: $SLURM_JOB_ID"
echo "MODEL: $MODEL"

echo "Installing requirements..."
cd $BASE
python -m venv .venv
source ./.venv/bin/activate
pip install --quiet -r "$BASE/requirements/requirements-cuda.txt"

echo "===== Training started at $(date) ====="
CUDA_VISIBLE_DEVICES=0 python -u -m "src.run_train_${MODEL}" --run-dir "$RUN_DIR"
echo "===== Training finished at $(date) ====="